package main

import (
	"fmt"
	"io"
	"math"
	"sort"
	"strconv"
	"strings"
	"time"
)

// commas renders 402360 as "402,360". Six-figure request counts are the norm
// here and unseparated digits are genuinely hard to compare between reports.
func commas(n int) string {
	s := strconv.Itoa(n)
	neg := strings.HasPrefix(s, "-")
	s = strings.TrimPrefix(s, "-")
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	if neg {
		return "-" + string(out)
	}
	return string(out)
}

func f1(v float64) string { return strconv.FormatFloat(v, 'f', 1, 64) }

// f4 is used for rates. Two decimals is not enough once a run is clean: 99.99%
// and 99.9994% describe very different services and both round to "99.99%".
func f4(v float64) string { return strconv.FormatFloat(v, 'f', 4, 64) }

// rps groups the thousands in a throughput figure. A bare "13412.0" sitting next
// to a comma-grouped request count is needlessly hard to read.
func rps(v float64) string {
	neg := v < 0
	if neg {
		v = -v
	}
	whole := int(v)
	out := commas(whole) + strings.TrimPrefix(strconv.FormatFloat(v-float64(whole), 'f', 1, 64), "0")
	if neg {
		return "-" + out
	}
	return out
}

// msStr matches the harness's own latency formatting so a report and the stdout
// it came from read the same.
func msStr(v float64) string { return f1(v) + "ms" }

func writeReport(w io.Writer, o opts, s summary, cpu []cpuSample, cpuErr error) {
	p := s.headline()

	writeHeader(w, o, s, p)
	writeSummaryTable(w, o, p)
	writeTailLatency(w, s, p)
	writeHeadroom(w, o, p)
	writeErrorRate(w, p)
	writeSaturation(w, o, p, cpu, cpuErr)
	writeOtherPhases(w, s, p)

	fmt.Fprintf(w, "\n---\n\n_Generated by `cmd/loadreport` from `%s`. See `docs/LOADTEST.md` for how to read this._\n",
		o.jsonPath)
}

func writeHeader(w io.Writer, o opts, s summary, p phase) {
	fmt.Fprintf(w, "# Load test — concurrency %d\n\n", o.concurrency)

	loop := fmt.Sprintf("closed loop, %d virtual users, think=%s", o.concurrency, s.Think)
	if !s.ClosedLoop {
		loop = fmt.Sprintf("open loop, offered %s req/s", f1(s.OfferedRate))
	}

	endpoint := s.Path
	if endpoint == "" {
		endpoint = "(default for target " + s.Target + ")"
	}

	fmt.Fprintln(w, "| | |")
	fmt.Fprintln(w, "|---|---|")
	fmt.Fprintf(w, "| Run started (UTC) | %s |\n", s.StartedUTC.Format(time.RFC3339))
	fmt.Fprintf(w, "| Concurrency | %d |\n", o.concurrency)
	fmt.Fprintf(w, "| Target | `%s` via `%s` |\n", endpoint, s.URL)
	fmt.Fprintf(w, "| Measured window | %s (%s warmup discarded) |\n", s.Duration, s.Warmup)
	fmt.Fprintf(w, "| Load model | %s |\n", loop)
	fmt.Fprintf(w, "| Per-request timeout | %s |\n", s.Timeout)
	fmt.Fprintf(w, "| Phase reported | `%s` |\n", p.Name)
	fmt.Fprintf(w, "| Cores under test | %s (%g allocated) |\n", o.coreRange, o.cores)
}

func writeSummaryTable(w io.Writer, o opts, p phase) {
	fmt.Fprintf(w, "\n## Summary\n\n")
	fmt.Fprintln(w, "| Concurrency | Throughput (req/s) | p99 latency | Error rate | Total requests | Failed requests |")
	fmt.Fprintln(w, "|---|---|---|---|---|---|")
	fmt.Fprintf(w, "| %d | %s | %s | %s | %s | %s |\n",
		o.concurrency,
		rps(p.RPS),
		msStr(p.All.P99),
		pctStr(p.Failed, p.TotalRequests),
		commas(p.TotalRequests),
		commas(p.Failed))
	fmt.Fprintf(w, "\nThroughput counts every request that completed inside the measured window; "+
		"%s req/s of that answered %d. p99 is over **all** requests, failures included.\n",
		rps(p.AcceptedRPS), p.OkStatus)
}

func writeTailLatency(w io.Writer, s summary, p phase) {
	fmt.Fprintf(w, "\n## Tail latency\n\n")
	fmt.Fprintln(w, "| Distribution | n | min | p50 | p95 | p99 | p99.9 | max | mean |")
	fmt.Fprintln(w, "|---|---|---|---|---|---|---|---|---|")
	latRow(w, "All requests", p.All)
	latRow(w, fmt.Sprintf("%d accepted", p.OkStatus), p.Acc)

	fmt.Fprintf(w, "\n**All requests** is the honest headline: it includes failed and timed-out "+
		"requests at their measured latency. Reading the accepted-only row instead caps the tail "+
		"at the %s timeout and lets percentiles *improve* under load as the slowest requests drop "+
		"out of the set.\n", s.Timeout)

	if p.Censored {
		fmt.Fprintf(w, "\n> WARNING: **latency is censored at the %s timeout.** The slowest request sat at "+
			"the timeout, so everything slower failed and was recorded at that value — p99.9 and max are "+
			"floors, not measurements. Re-run with a larger `TIMEOUT` to see how bad the tail really gets.\n",
			s.Timeout)
	}
}

func latRow(w io.Writer, label string, l latencyStats) {
	if l.N == 0 {
		fmt.Fprintf(w, "| %s | 0 | — | — | — | — | — | — | — |\n", label)
		return
	}
	fmt.Fprintf(w, "| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n",
		label, commas(l.N),
		msStr(l.Min), msStr(l.P50), msStr(l.P95), msStr(l.P99), msStr(l.P999), msStr(l.Max), msStr(l.Mean))
}

func writeHeadroom(w io.Writer, o opts, p phase) {
	fmt.Fprintf(w, "\n## Headroom\n\n")

	util := p.RPS / o.ceiling * 100
	half := o.ceiling * 0.5

	fmt.Fprintf(w, "**Ceiling used: %s req/s — the %s.**\n\n", commas(int(o.ceiling)), o.ceilingLabel)
	if o.ceilingWhy != "" {
		fmt.Fprintf(w, "%s\n\n", o.ceilingWhy)
	}

	fmt.Fprintln(w, "| | |")
	fmt.Fprintln(w, "|---|---|")
	fmt.Fprintf(w, "| Achieved | %s req/s |\n", rps(p.RPS))
	fmt.Fprintf(w, "| Ceiling | %s req/s |\n", commas(int(o.ceiling)))
	fmt.Fprintf(w, "| Utilization | **%s%%** |\n", f1(util))
	fmt.Fprintf(w, "| 50%%-of-capacity target | %s req/s |\n", commas(int(half)))
	fmt.Fprintf(w, "| Remaining headroom | %s req/s |\n", rps(o.ceiling-p.RPS))

	switch {
	case util > 100:
		fmt.Fprintf(w, "\n> **OVER THE CEILING (%s%%).** This run beat the recorded ceiling, which means the "+
			"ceiling is stale rather than that headroom is negative — re-baseline before trusting any "+
			"headroom figure here.\n", f1(util))
	case util > 50:
		fmt.Fprintf(w, "\n> **OVER 50%% OF CAPACITY.** At %s req/s this run uses %s%% of the ceiling, past the "+
			"50%% rule-of-thumb target of %s req/s. Only %s req/s of headroom is left, so a spike of much "+
			"more than %s%% has nowhere to go — and losing one of the three replicas would put the "+
			"remaining two over the line.\n",
			rps(p.RPS), f1(util), commas(int(half)), rps(o.ceiling-p.RPS), f1(100/util*100-100))
	default:
		fmt.Fprintf(w, "\n> **Within the 50%% rule of thumb.** At %s req/s this run uses %s%% of the ceiling, "+
			"under the %s req/s target, leaving %s req/s of headroom.\n",
			rps(p.RPS), f1(util), commas(int(half)), rps(o.ceiling-p.RPS))
	}
}

func writeErrorRate(w io.Writer, p phase) {
	fmt.Fprintf(w, "\n## Error rate\n\n")

	total := p.TotalRequests
	fmt.Fprintln(w, "| | |")
	fmt.Fprintln(w, "|---|---|")
	fmt.Fprintf(w, "| Successful (%d) | %s / %s |\n", p.OkStatus, commas(p.Accepted), commas(total))
	fmt.Fprintf(w, "| Success rate | **%s** |\n", pctStr(p.Accepted, total))
	fmt.Fprintf(w, "| Failed | %s (%s) |\n", commas(p.Failed), pctStr(p.Failed, total))
	fmt.Fprintf(w, "| — transport errors | %s |\n", commas(p.TransportErrors))
	fmt.Fprintf(w, "| — non-%d responses | %s |\n", p.OkStatus, commas(p.NonOK))
	fmt.Fprintf(w, "| Availability | %s |\n", nines(p.Accepted, total))

	fmt.Fprintf(w, "\nA request counts as failed if it errored in transport **or** did not answer %d. "+
		"The two are separated because a 502 and a timeout are both failures with entirely different causes.\n",
		p.OkStatus)

	if len(p.Statuses) > 0 {
		fmt.Fprintf(w, "\n**Status codes:** ")
		codes := make([]string, 0, len(p.Statuses))
		for c := range p.Statuses {
			codes = append(codes, c)
		}
		sort.Strings(codes)
		parts := make([]string, 0, len(codes))
		for _, c := range codes {
			parts = append(parts, fmt.Sprintf("`%s`=%s", c, commas(p.Statuses[c])))
		}
		fmt.Fprintln(w, strings.Join(parts, "  "))
	}

	if n := nonZero(p.Errors); len(n) > 0 {
		fmt.Fprintf(w, "\n**Transport error breakdown:** ")
		parts := make([]string, 0, len(n))
		for _, k := range n {
			parts = append(parts, fmt.Sprintf("%s=%s", k, commas(p.Errors[k])))
		}
		fmt.Fprintln(w, strings.Join(parts, "  "))
	}
}

func writeSaturation(w io.Writer, o opts, p phase, cpu []cpuSample, cpuErr error) {
	fmt.Fprintf(w, "\n## Saturation\n\n")

	if cpuErr != nil || len(cpu) == 0 {
		fmt.Fprintf(w, "> WARNING: **no CPU samples for this run** (%v). Throughput, latency and error rate "+
			"above are unaffected, but there is no way to tell from this report whether the throughput "+
			"figure is a ceiling or just the load that was offered.\n", cpuErr)
		return
	}

	agg := aggregate(cpu, p.WindowStartUTC, p.WindowEndUTC)
	budget := o.cores * 100

	fmt.Fprintf(w, "Cores `%s` — %g cores allocated, so a fully saturated set reads **%g%%** in docker "+
		"terms (100%% is one busy core). The load generator is pinned outside this set and is excluded.\n\n",
		o.coreRange, o.cores, budget)

	fmt.Fprintln(w, "| Container | avg CPU% | peak CPU% | polls |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, c := range agg.perContainer {
		fmt.Fprintf(w, "| `%s` | %s | %s | %d |\n", c.name, f1(c.avg), f1(c.peak), c.n)
	}
	fmt.Fprintf(w, "| **Combined** | **%s** | **%s** | %d |\n", f1(agg.combinedAvg), f1(agg.combinedPeak), agg.polls)

	fmt.Fprintf(w, "\n| | |\n|---|---|\n")
	fmt.Fprintf(w, "| Saturation of %g cores (avg) | **%s%%** |\n", o.cores, f1(agg.combinedAvg/budget*100))
	fmt.Fprintf(w, "| Saturation of %g cores (peak) | **%s%%** |\n", o.cores, f1(agg.combinedPeak/budget*100))
	fmt.Fprintf(w, "| Polls counted | %d |\n", agg.polls)
	if agg.interval > 0 {
		fmt.Fprintf(w, "| Effective poll interval | %s |\n", agg.interval.Round(10*time.Millisecond))
	}

	if !agg.windowed {
		fmt.Fprintf(w, "\n> WARNING: **window alignment unavailable.** Fewer than three CPU polls landed "+
			"inside the measured window `%s`–`%s`, so these figures cover the whole collection period "+
			"including warmup and drain, and understate the load during the window. The usual cause is "+
			"clock skew between the host running the collector and the container clock the harness stamps.\n",
			p.WindowStartUTC.Format(time.RFC3339), p.WindowEndUTC.Format(time.RFC3339))
	} else {
		fmt.Fprintf(w, "\nSamples are intersected with the measured window `%s`–`%s`, so saturation covers "+
			"exactly the seconds the throughput and latency figures came from.\n",
			p.WindowStartUTC.Format(time.RFC3339), p.WindowEndUTC.Format(time.RFC3339))
	}

	sat := agg.combinedAvg / budget * 100
	switch {
	case sat >= 90:
		fmt.Fprintln(w, "\n> The cores are saturated. The throughput figure above is a real ceiling — adding "+
			"concurrency will buy latency, not requests per second.")
	case sat >= 60:
		fmt.Fprintln(w, "\n> The cores are working hard but not pinned. There is probably some throughput "+
			"left, and the next concurrency step up should show where it runs out.")
	default:
		fmt.Fprintln(w, "\n> The cores are far from saturated, so the throughput above is the load that was "+
			"*offered*, not a capacity limit. Raise `CONCURRENCY` before drawing any conclusion about capacity.")
	}
}

// writeOtherPhases records any phase that was measured but is not the one the
// report headlines — currently only the login limiter phase. Its numbers are
// real, but headroom against a capacity ceiling would be meaningless for a phase
// whose whole job is to be throttled.
func writeOtherPhases(w io.Writer, s summary, headline phase) {
	for _, p := range s.Phases {
		if p.Name == headline.Name {
			continue
		}
		fmt.Fprintf(w, "\n## Other phase: %s\n\n", p.Name)
		fmt.Fprintf(w, "%s requests, %s req/s, p99 %s, %s failed (%s).\n",
			commas(p.TotalRequests), rps(p.RPS), msStr(p.All.P99), commas(p.Failed), pctStr(p.Failed, p.TotalRequests))
		fmt.Fprintln(w, "\nNo headroom figure: this phase drives a deliberately throttled path, so "+
			"utilization against a capacity ceiling would not mean anything.")
	}
}

func pctStr(n, total int) string {
	if total == 0 {
		return "n/a"
	}
	return f4(float64(n)/float64(total)*100) + "%"
}

// nines renders availability the way an SLO is usually quoted.
//
// A run with no failures has infinite nines, which is not a result. What it can
// honestly say is a bound: N requests without a failure cannot demonstrate more
// than about log10(N) nines however clean it looked.
func nines(accepted, total int) string {
	if total == 0 {
		return "n/a"
	}
	failed := total - accepted
	if failed <= 0 {
		return fmt.Sprintf("no failures in %s requests — bounds availability at >= %s nines, which is "+
			"the most a sample this size can show", commas(total), f1(math.Log10(float64(total))))
	}
	ratio := float64(accepted) / float64(total)
	return fmt.Sprintf("%s nines (%s success)", f1(-math.Log10(1-ratio)), pctStr(accepted, total))
}

// nonZero returns the keys with a count above zero, sorted, so an empty
// breakdown prints nothing instead of a row of zeroes.
func nonZero(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k, v := range m {
		if v > 0 {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}
